config/routes.rb
Rails.application.routes.draw do
  resources :goods
  devise_for :users , :controllers => { registrations: 'registrations' }
  resources :consent_forms
  resources :consent_form_types
  resources :donations
  resources :cities
  resources :states
  resources :countries
  resources :volunteers
  resources :suppliers
  resources :consumers
  resources :donors
 
  resources :donation_campaigns
  resources :signups
  resources :address_cocoons
  resources :person_cocoons
  resources :services
  resources :ranks
  resources :form_contacts
  resources :addresses
  resources :private_place_types
  resources :public_places
  resources :supply_food_configurations
  resources :postal_code_hints
  get 'postal_code_hints_search', to: 'postal_code_hints#search'
  post 'postal_code_hints_search', to: 'postal_code_hints#search'
  resources :measure_units
  resources :good_types
  resources :levels
  resources :logs
  resources :user_types
  resources :address_types
  resources :public_place_types
  resources :person_types
  resources :ic_types
  resources :people
  resources :assignment_types
  resources :form_contacts
    
  root 'splash#splash'
  get 'home', to: 'home#home'
  get 'about', to: 'home#about'
  get 'my_jquery_test', to: 'home#my_jquery_test'
  get 'point_hunger', to: 'home#point_hunger'
  
  if Rails.env.development?
       get 'testbootstrap', to: 'home#testbootstrap'
  end
 
    
 
    
  get 'foodhandling', to: 'home#foodhandling'
  get 'news', to: 'home#news'
  get 'legal', to: 'home#legal'
  get 'services', to: 'home#services'
  get 'valueofdonation', to: 'home#valueofdonation'
    
  get 'management', to: 'management#management'
    
  get 'donor', to: 'donor#donor'
  get 'donate', to: 'donor#donate'
  get 'track_donations', to: 'donor#track_donations'
  get 'list_donations', to: 'donor#list_donations'

  get 'donor', to: 'donor#donor'
    
  get 'volunteer', to: 'volunteers#menu'

    
    
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/public_place.rb
class PublicPlace < ApplicationRecord
  belongs_to :public_place_type
  belongs_to :postal_code_hint
  

accepts_nested_attributes_for :postal_code_hint, reject_if: :all_blank, allow_destroy: false
end

app/models/public_place_type.rb
class PublicPlaceType < ApplicationRecord
    has_many :public_place
end

app/controllers/public_places_controller.rb
class PublicPlacesController < ApplicationController
  before_action :set_public_place, only: [:show, :edit, :update, :destroy]


  # GET /public_places
  # GET /public_places.json
  def index
    @public_places = PublicPlace.all
  end

  def search
      render partial: 'postal_code_hint/search'
  end
    
  # GET /public_places/1
  # GET /public_places/1.json
  def show
  end

  # GET /public_places/new
  def new
    @public_place = PublicPlace.new
  end

  # GET /public_places/1/edit
  def edit

  end

  # POST /public_places
  # POST /public_places.json
  def create
    @public_place = PublicPlace.new(public_place_params)

    respond_to do |format|
       
      if @public_place.save
        format.html { redirect_to @public_place, notice: 'Public place was successfully created.' }
        format.json { render :show, status: :created, location: @public_place }
      else
        format.html { render :new }
        format.json { render json: @public_place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /public_places/1
  # PATCH/PUT /public_places/1.json
  def update
    respond_to do |format|
      if @public_place.update(public_place_params)
        format.html { redirect_to @public_place, notice: 'Public place was successfully updated.' }
        format.json { render :show, status: :ok, location: @public_place }
      else
        format.html { render :edit }
        format.json { render json: @public_place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /public_places/1
  # DELETE /public_places/1.json
  def destroy
    @public_place.destroy
    respond_to do |format|
      format.html { redirect_to public_places_url, notice: 'Public place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_public_place
      @public_place = PublicPlace.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def public_place_params
      params.require(:public_place).permit(:name, :public_place_type_id, :postal_code_hint_id,:number, public_place_type_attributes: [ :public_place_name,:hint, :code])
    end
end

app/helpers/public_places_helper.rb
module PublicPlacesHelper
end

app/views/public_places/_form.html.erb
<script  type="text/JavaScript">
    function httpGet(theUrl)
    {
        
    var xmlHttp = null;

    xmlHttp = new XMLHttpRequest();
    xmlHttp.open( "GET", theUrl, false );
    xmlHttp.send( null );
        
    return xmlHttp.responseText;
    }
  
function search_by_code(event) {
    var search_text = document.getElementById("search_code").value;
    var search_result_url = "/postal_code_hints_search?search=code&code=" + search_text ;
    document.getElementById("result_search").innerHTML=httpGet(search_result_url);
    //event.preventDefault();
    return false;
}
    function search_by_public_place_name(event) {
    var search_text = document.getElementById("search_public_place_name").value;
    var search_result_url = "/postal_code_hints_search?search=public_place_name&public_place_name=" + search_text ;
    document.getElementById("result_search").innerHTML=httpGet(search_result_url);
    //event.preventDefault();
    return false;
}
    
    function set_postal_code_hint(new_id,new_hint, new_code,new_public_place_name){
        document.getElementById("postal_code_hint_id").value=new_id;
        document.getElementById("postal_code_hint_code").value=new_code;
        document.getElementById("postal_code_hint_public_place_name").value=new_public_place_name;
        document.getElementById("postal_code_hint_hint").value=new_hint;

        document.getElementById("search_public_place_name").value=new_public_place_name;
        document.getElementById("lbl_pch_code").innerHTML=new_code;
        document.getElementById("lbl_pch_hint").innerHTML=new_hint
        document.getElementById("lbl_pch_public_place").innerHTML=new_public_place_name;
        return false;
    }
    

</script>
<%= form_with(model: public_place,class: "form-horizontal", id: "public_place_form") do |form| %>
  <% if public_place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(public_place.errors.count, "error") %> prohibited this public_place from being saved:</h2>

      <ul>
      <% public_place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="form-group field">
            <%= form.label :public_place_type_id, class:"control-label" %>
            <%= collection_select( :public_place,:public_place_type_id,  PublicPlaceType.all, :id, :name,  {:prompt => "Select a public place type"}, {:class=>"form-control"} ) %>
    </div>

    <div class="form-group field">
        <%= form.label :name, class:"control-label" %>
        <%= form.text_field :name, placeholder:"Name of the public place", class:"form-control col-sm",id:"search_public_place_name" %>
         <%= link_to  "" , remote: true, class: 'btn btn-xs btn-success',  onmousedown: "search_by_public_place_name(event);"  do %>
            <i class="fa fa-search"></i> Hint
        <%end%>
    </div>

    <div class="form-group field">
        <%= form.label :neighbourhood, class:"control-label" %>
        <%= form.text_field :neighbourhood, placeholder:"neigbourhood, community", class:"form-control col-sm",id:"search_public_place_name" %>
    </div>

    <div class="form-group field">
        <%= form.label :number %>
        <%= form.text_field :number, placeholder:"number of the public place", class:"form-control col-sm" %>
    </div>
<hr>
        <div id='postal_code_hint'>
            Postal code :
            <label id="lbl_pch_code" >
                <% if !public_place.postal_code_hint.nil? %>
                <%= @public_place.postal_code_hint[:code] %>
                <% end %>
            </label>-
            <label id="lbl_pch_public_place">
                <% if !public_place.postal_code_hint.nil? %>
                <%= @public_place.postal_code_hint[:public_place] %>
                <% end %>
            </label>&nbsp;
            <label id="lbl_pch_hint">
                <% if !public_place.postal_code_hint.nil? %>
                <%= @public_place.postal_code_hint[:hint] %>
                <% end %>
            </label>
        </div>
<hr>
<div>
    <%= form.text_field :postal_code_hint_id, class:"form-control col-sm" ,id:"postal_code_hint_id" %>
    <%= form.text_field :postal_code_hint_code, class:"form-control col-sm" ,id:"postal_code_hint_code" %>
    <%= form.text_field :postal_code_hint_public_place_name, class:"form-control col-sm" ,id:"postal_code_hint_public_place_name" %>
    <%= form.text_field :postal_code_hint_hint, class:"form-control col-sm" ,id:"postal_code_hint_hint" %>
</div>

<%= render partial: "/postal_code_hints/city" , locals: {form: form} %>

    <div class="">
        <%= form.label "Postal code search" %>
        <%= form.text_field :postal_code_hint_search, class:"form-control col-sm" , id:"search_code" %>
        
        <%= link_to "", remote: true, class: 'btn btn-xs btn-success',  onmousedown: "search_by_code(event);"  do %>
            <i class="fa fa-search"></i> Code
        <%end%>
        <div id="result_search">
          <%= render "postal_code_hints/search" %>
        </div>
    </div>


  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/public_places/edit.html.erb
<h1>Editing Public Place</h1>

<%= render 'form', public_place: @public_place %>

<%= link_to 'Show', @public_place %> |
<%= link_to 'Back', public_places_path %>

app/views/public_places/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Public Places</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Public place type</th>
      <th scope="col">Number</th>
      <th scope="col">Postal code hint</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @public_places.each do |public_place| %>
      <tr scope="row">
        <td><%= public_place.public_place_type.name %></td>
        <td><%= public_place.name %></td>
        <td><%= public_place.number %></td>
        <td><%= public_place.postal_code_hint.code %></td>
        <td><%= link_to 'Show', public_place %></td>
        <td><%= link_to 'Edit', edit_public_place_path(public_place) %></td>
        <td><%= link_to 'Destroy', public_place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Public Place', new_public_place_path %>

app/views/public_places/new.html.erb
<h1>New Public Place</h1>

<%= render 'form', public_place: @public_place %>

<%= link_to 'Back', public_places_path %>

app/views/public_places/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @public_place.name %>
</p>

<p>
  <strong>Public place type:</strong>
  <%= @public_place.public_place_type %>
</p>

<p>
  <strong>Postal code hint:</strong>
  <%= @public_place.postal_code_hint %>
</p>

<%= link_to 'Edit', edit_public_place_path(@public_place) %> |
<%= link_to 'Back', public_places_path %>