config/routes.rb
Rails.application.routes.draw do
  resources :goods
  devise_for :users , :controllers => { registrations: 'registrations' }
  resources :consent_forms
  resources :consent_form_types
  resources :donations
  resources :cities
  resources :states
  resources :countries
  resources :volunteers
  resources :suppliers
  resources :consumers
  resources :donors
 
  resources :donation_campaigns
  resources :signups
  resources :address_cocoons
  resources :person_cocoons
  resources :services
  resources :ranks
  resources :form_contacts
  resources :addresses
  resources :private_place_types
  resources :public_places
  resources :supply_food_configurations
  resources :postal_code_hints
  get 'postal_code_hints_search', to: 'postal_code_hints#search'
  post 'postal_code_hints_search', to: 'postal_code_hints#search'
  resources :measure_units
  resources :good_types
  resources :levels
  resources :logs
  resources :user_types
  resources :address_types
  resources :public_place_types
  resources :person_types
  resources :ic_types
  resources :people
  resources :assignment_types
  resources :form_contacts
    
  root 'splash#splash'
  get 'home', to: 'home#home'
  get 'about', to: 'home#about'
  get 'my_jquery_test', to: 'home#my_jquery_test'
  get 'point_hunger', to: 'home#point_hunger'
  
  if Rails.env.development?
       get 'testbootstrap', to: 'home#testbootstrap'
  end
 
    
 
    
  get 'foodhandling', to: 'home#foodhandling'
  get 'news', to: 'home#news'
  get 'legal', to: 'home#legal'
  get 'services', to: 'home#services'
  get 'valueofdonation', to: 'home#valueofdonation'
    
  get 'management', to: 'management#management'
    
  get 'donor', to: 'donor#donor'
  get 'donate', to: 'donor#donate'
  get 'track_donations', to: 'donor#track_donations'
  get 'list_donations', to: 'donor#list_donations'

  get 'donor', to: 'donor#donor'
    
  get 'volunteer', to: 'volunteers#menu'

    
    
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :public_place
  belongs_to :private_place_type
  has_and_belongs_to_many :people
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :state
  belongs_to :country
end

app/models/consumer.rb
class Consumer < ApplicationRecord
  belongs_to :person
end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/donation.rb
class Donation < ApplicationRecord
 belongs_to :donor 
 has_many :volunteer 
 has_many :goods, inverse_of: :donation, dependent: :destroy
 accepts_nested_attributes_for :goods, reject_if: :all_blank, allow_destroy: true
    
 def status
        "Not available"
 end
end

app/models/donor.rb
class Donor < ApplicationRecord
    belongs_to :user
    has_many :donations
    
    def getStartLevel
        @@donor_start_level ||="#{SupplyFoodConfiguration.find_by(name: "Donor start level").description}"
    end
end

app/models/good.rb
class Good < ApplicationRecord
  belongs_to :measure_unit
  belongs_to :good_type
  belongs_to :donation
  belongs_to :address
end

app/models/good_type.rb
class GoodType < ApplicationRecord
  #belongs_to :good_type
  has_ancestry
  #belongs_to :parent, class_name: "GoodType"
  #has_many :children, class_name: "GoodType", foreign_key: "parent_id"
end

app/models/ic_type.rb
class IcType < ApplicationRecord
    validates :name, presence:true,  length: {minimum:3, maximum:50}
    validates_uniqueness_of :name
    has_many :person
end

app/models/level.rb
class Level < ApplicationRecord
end

app/models/log.rb
class Log < ApplicationRecord
end

app/models/person.rb
class Person < ApplicationRecord
  #commented to a more flexible user registration
  belongs_to :person_type
  belongs_to :ic_type
  has_and_belongs_to_many :addresses
  accepts_nested_attributes_for :addresses, allow_destroy: false
end

app/models/rank.rb
class Rank < ApplicationRecord
    has_and_belongs_to_many :volunteers
end

app/models/service.rb
class Service < ApplicationRecord
end

app/models/sqllog.rb
class Sqllog < ApplicationRecord
end

app/models/state.rb
class State < ApplicationRecord
  belongs_to :country
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  belongs_to :person
end

app/models/user.rb
class User < ApplicationRecord
  has_one :person
  belongs_to :volunteer
  belongs_to :donor
  has_one :supplier
  has_one :consumer
  has_many :consent_form


  after_create :add_person, :add_unsigned_consent_forms
    
   def add_person
     person = Person.new
     person.email =  :email
     person.save
   end    
    
   def add_unsigned_consent_forms
       #add donor consent form
       add_unsigned_donor_consent_forms

       #add supplier consent form
       add_unsigned_supplier_consent_forms
       
       #add volunteer consent form
       add_unsigned_volunteer_consent_forms
     
       #add consumer consent form
       add_unsigned_consumer_consent_forms

   end  
    
    def add_unsigned_donor_consent_forms
       donor_consent = ConsentForm.new
       donor_consent.consent_form_type = ConsentFormType.find_by description: "Donor"
       donor_consent.user = self
       donor_consent.save
    end
    
    def add_unsigned_supplier_consent_forms
       supplier_consent = ConsentForm.new
       supplier_consent.consent_form_type = ConsentFormType.find_by description: "Supplier"
       supplier_consent.user = self
       supplier_consent.save
    end
    
    def add_unsigned_volunteer_consent_forms
       volunteer_consent = ConsentForm.new
       volunteer_consent.consent_form_type = ConsentFormType.find_by description: "Volunteer"
       volunteer_consent.user = self  
       volunteer_consent.save
    end
    
    def add_unsigned_consumer_consent_forms
       consumer_consent = ConsentForm.new
       consumer_consent.consent_form_type = ConsentFormType.find_by description: "Donee"
       consumer_consent.user = self  
       consumer_consent.save
    end
    
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user_type.rb
class UserType < ApplicationRecord
    has_many :user
end

app/models/volunteer.rb
class Volunteer < ApplicationRecord
  
    
    def getStartRank
        @@donor_start_Rank||="#{SupplyFoodConfiguration.find_by(name: "Volunteer start rank").description}"
    end
end

app/controllers/management_controller.rb
class ManagementController < ApplicationController
    
def management
end
    


    
end

app/views/management/_tab-end.html.erb
    </div>
</div>

app/views/management/_tab.html.erb
<div class="row">
    <div class="col-xs-12">
<%
 @linkClass = "nav-link bg-light border border-secondary text-dark "
 if current_page?(controller: 'address_types', action: 'index')
    @address_types_active = ' active' 
 elsif current_page?(controller: 'assignment_types', action: 'index')
    @assignment_types_active = ' active' 
 elsif current_page?(controller: 'supply_food_configurations', action: 'index')
     @supply_food_configurations_active = ' active' 
 elsif current_page?(controller: 'consent_form_types', action: 'index')
     @consent_form_types_active = ' active' 
 elsif current_page?(controller: 'form_contacts', action: 'index') 
     @form_contacts_active= ' active' 
 elsif  current_page?(controller: 'ic_types', action: 'index') 
     @ic_types_active= ' active' 
 elsif current_page?(controller: 'good_types', action: 'index')
     @good_types_active= ' active' 
elsif current_page?(controller: 'levels', action: 'index')
     @levels_active= ' active' 
elsif current_page?(controller: 'logs', action: 'index')
     @logs_active= ' active' 
elsif current_page?(controller: 'measure_units', action: 'index')
     @measure_units_active= ' active' 
elsif current_page?(controller: 'people', action: 'index')
     @people_active= ' active' 
elsif current_page?(controller: 'person_types', action: 'index')
     @person_types_active= ' active' 
elsif current_page?(controller: 'private_place_types', action: 'index')
     @private_place_types_active= ' active' 
elsif current_page?(controller: 'public_place_types', action: 'index')
     @public_place_types_active= ' active' 
elsif current_page?(controller: 'postal_code_hints', action: 'index')
     @postal_code_hints_active= ' active' 
#elsif current_page?(controller: 'users', action: 'index')
#     @users_active= ' active' 
elsif current_page?(controller: 'user_types', action: 'index')
     @user_types_active= ' active' 
 end
%>
<h1>Management</h1>
<ul class="nav nav-tabs sfnav bg-light border border-secondary" >
  <li class="nav-item " >
      <%= link_to 'Address types', address_types_url , class:"#{@linkClass} #{@address_types_active}" %>
  </li>
    
  <li class="nav-item" >
      <%= link_to 'Assignment Type', assignment_types_url , class:"#{@linkClass} #{@assignment_types_active}" %>
  </li>
  <li class="nav-item"  > 
      <%= link_to 'Configurations', supply_food_configurations_url, class:"#{@linkClass}  #{@supply_food_configurations_active}" %>
  </li>
  <li class="nav-item"  > 
      <%= link_to 'Consent Form Types', consent_form_types_url, class:"#{@linkClass}  #{@consent_form_types_active}" %>
  </li>
  <li class="nav-item" >
      <%= link_to 'Contact Messages', form_contacts_url, class:"#{@linkClass}  #{@form_contacts_active}"  %>
  </li>
  <li class="nav-item" >
      <%= link_to 'Identification Card Types', ic_types_url, class:"#{@linkClass}  #{@ic_types_active}"  %>
  </li>
  <li class="nav-item"  >
      <%= link_to 'Good Types', good_types_url, class:"#{@linkClass}  #{@good_types_active}"  %>
  </li>
    
  <li class="nav-item"  >
      <%= link_to 'Levels', levels_url, class:"#{@linkClass}  #{@levels_active}"  %>
  </li>
  <li class="nav-item" >
      <%= link_to 'Logs', logs_url, class:"#{@linkClass}  #{@logs_active}"  %>
  </li>
  <li class="nav-item" >
      <%= link_to 'Measure Units', measure_units_url, class:"#{@linkClass}  #{@measure_units_active}"  %>
  </li>
  <li class="nav-item" >
      <%= link_to 'People', people_url, class:"#{@linkClass} #{@people_active}"   %>
  </li>
  <li class="nav-item" >
      <%= link_to 'Person Types', person_types_url, class:"#{@linkClass} #{@person_types_active}"  %>
  </li>
  <li class="nav-item" >
      <%= link_to 'Private place types',private_place_types_url, class:"#{@linkClass} #{@private_place_types_active}"  %>
  </li>
  <li class="nav-item" >
      <%= link_to 'Public place types',public_place_types_url , class:"#{@linkClass} #{@public_place_types_active}" %>
  </li>
   <li class="nav-item" >
      <%= link_to 'Postal Code Hints', postal_code_hints_url, class:"#{@linkClass} #{@postal_code_hints_active}"  %>
  </li>
<!--
  <li class="nav-item" >
      <%# link_to 'Users', users_url, class:"#{@linkClass} #{@users_active}"  %>
  </li>
-->
  <li class="nav-item" >
      <%= link_to 'User types', user_types_url, class:"#{@linkClass} #{@user_types_active}"  %>
  </li>
</ul>
<!--
<script type="application/javascript">
    $(document).ready(function(){
        $("li a").load(function(){
            $(this).addClass("active");
        });
    });
</script>
-->
    </div>
</div>
<div class="row  bg-light border border-secondary" id="grid_container">
    <div class="col-sm-12">


app/views/management/management.html.erb

<%= render 'management/tab' %>
<h2>Management</h2>
<p>Manage the site main data. Be careful with the alteration made on this section , they will be reflected on the user experience.</p>

<script>
$( function() {
$( "#accordion" ).accordion({
  collapsible: true,  active:false
});
} );
</script>
<div id="accordion">
    <h3>Manager</h3>
    <div>
        <li>Operations</li>
        <ul>
            <li>Donation Campaign</li>
            <ul>
                <li>Extend donation campaing</li>
                <li>End donation campaign</li>
                <li>Donation campaign diary</li>
            </ul>
            <li>Aknowledge lost</li>
        </ul>
        <li>Team management</li>
            <ul>
                <li>Volunteers</li>
                <ul>
                    <li>Volunteers-to-be</li>
                    <li>List Volunteers</li>
                    <li>Admit Volunteer</li>
                    <li>Dismiss Volunteer</li>
                    <li>Send Thanks to Volunteer</li>
                    <li>Letter of recommendation</li>
                </ul>
                <li>Suppliers</li>
                <ul>
                    <li>Suppliers-to-be</li>
                    <li>List Suppliers</li>
                    <li>Admit Supplier</li>
                    <li>Pay Supplier</li>
                    <li>Dismiss Supplier</li>
                    <li>Letter of recommendation</li>
                </ul>
                <li>Training Schedule</li>
            </ul>
        <li>Reports</li>
        <ul>
            <li>Donor by donations</li>
            <li>Collections by volunteer</li>
            <li>Collections by supplier</li>
            <li>Donation by region</li>
            <li>Donations by good type</li>
            <li>Deliveries by volunteer</li>
            <li>Deliveries by consumer</li>
            <li>Storages and Inventories</li>
	    <li>Pending donations</li>
        </ul>
    </div>
    <h3>Volunteer</h3>
    <div>
        <li>Call Center</li>
        <ul>
            <li>Respond donations call</li>
            <li>Direct mail</li>
            <ul>
                <li>Donation request</li>
                <li>Volunteer request</li>
            </ul>
        </ul>
        <li>Operations</li>
        <ul>
            <li>Check inventory</li>
            <li>Execute disposal</li>
        </ul>
        <li>Donation Campaign</li>
        <ul>
            <li>Collect donations</li>
            <li>Register consumer</li>
            <li>Deliver donation</li>
            <li>Add picture to donation campaign</li>
        </ul>
    </div>
    <h3>Courier</h3>
    <div>
        <li>Accept supply call</li>
        <li>Try reschedule supply call</li>
        <li>Refuse supply call</li>
        <li>End supply call with OK</li>
        <li>End supply call with concerns</li>
        <li>End supply call with fail</li>
    </div>
    <h3>Donee</h3>
    <div>
        <li>Ask for food</li>
        <li>Thanks for food</li>
        <li>Point food insecurity</li>
    </div>
</div>
<%= render 'management/tab-end' %>