config/routes.rb
Rails.application.routes.draw do
  resources :goods
  devise_for :users , :controllers => { registrations: 'registrations' }
  resources :consent_forms
  resources :consent_form_types
  resources :donations
  resources :cities
  resources :states
  resources :countries
  resources :volunteers
  resources :suppliers
  resources :consumers
  resources :donors
 
  resources :donation_campaigns
  resources :signups
  resources :address_cocoons
  resources :person_cocoons
  resources :services
  resources :ranks
  resources :form_contacts
  resources :addresses
  resources :private_place_types
  resources :public_places
  resources :supply_food_configurations
  resources :postal_code_hints
  get 'postal_code_hints_search', to: 'postal_code_hints#search'
  post 'postal_code_hints_search', to: 'postal_code_hints#search'
  resources :measure_units
  resources :good_types
  resources :levels
  resources :logs
  resources :user_types
  resources :address_types
  resources :public_place_types
  resources :person_types
  resources :ic_types
  resources :people
  resources :assignment_types
  resources :form_contacts
    
  root 'splash#splash'
  get 'home', to: 'home#home'
  get 'about', to: 'home#about'
  get 'my_jquery_test', to: 'home#my_jquery_test'
  get 'point_hunger', to: 'home#point_hunger'
  
  if Rails.env.development?
       get 'testbootstrap', to: 'home#testbootstrap'
  end
 
    
 
    
  get 'foodhandling', to: 'home#foodhandling'
  get 'news', to: 'home#news'
  get 'legal', to: 'home#legal'
  get 'services', to: 'home#services'
  get 'valueofdonation', to: 'home#valueofdonation'
    
  get 'management', to: 'management#management'
    
  get 'donor', to: 'donor#donor'
  get 'donate', to: 'donor#donate'
  get 'track_donations', to: 'donor#track_donations'
  get 'list_donations', to: 'donor#list_donations'

  get 'donor', to: 'donor#donor'
    
  get 'volunteer', to: 'volunteers#menu'

    
    
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :public_place
  belongs_to :private_place_type
  has_and_belongs_to_many :people
end

app/models/address_cocoon.rb
class AddressCocoon < ApplicationRecord
  belongs_to :person_cocoon
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :state
  belongs_to :country
end

app/models/consumer.rb
class Consumer < ApplicationRecord
  belongs_to :person
end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/donation.rb
class Donation < ApplicationRecord
 belongs_to :donor 
 has_many :volunteer 
 has_many :goods, inverse_of: :donation, dependent: :destroy
 accepts_nested_attributes_for :goods, reject_if: :all_blank, allow_destroy: true
    
 def status
        "Not available"
 end
end

app/models/donor.rb
class Donor < ApplicationRecord
    belongs_to :user
    has_many :donations
    
    def getStartLevel
        @@donor_start_level ||="#{SupplyFoodConfiguration.find_by(name: "Donor start level").description}"
    end
end

app/models/good.rb
class Good < ApplicationRecord
  belongs_to :measure_unit
  belongs_to :good_type
  belongs_to :donation
  belongs_to :address
end

app/models/good_type.rb
class GoodType < ApplicationRecord
  #belongs_to :good_type
  has_ancestry
  #belongs_to :parent, class_name: "GoodType"
  #has_many :children, class_name: "GoodType", foreign_key: "parent_id"
end

app/models/ic_type.rb
class IcType < ApplicationRecord
    validates :name, presence:true,  length: {minimum:3, maximum:50}
    validates_uniqueness_of :name
    has_many :person
end

app/models/level.rb
class Level < ApplicationRecord
end

app/models/log.rb
class Log < ApplicationRecord
end

app/models/person.rb
class Person < ApplicationRecord
  #commented to a more flexible user registration
  belongs_to :person_type
  belongs_to :ic_type
  has_and_belongs_to_many :addresses
  accepts_nested_attributes_for :addresses, allow_destroy: false
end

app/models/rank.rb
class Rank < ApplicationRecord
    has_and_belongs_to_many :volunteers
end

app/models/service.rb
class Service < ApplicationRecord
end

app/models/sqllog.rb
class Sqllog < ApplicationRecord
end

app/models/state.rb
class State < ApplicationRecord
  belongs_to :country
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  belongs_to :person
end

app/models/user.rb
class User < ApplicationRecord
  has_one :person
  belongs_to :volunteer
  belongs_to :donor
  has_one :supplier
  has_one :consumer
  has_many :consent_form


  after_create :add_person, :add_unsigned_consent_forms
    
   def add_person
     person = Person.new
     person.email =  :email
     person.save
   end    
    
   def add_unsigned_consent_forms
       #add donor consent form
       add_unsigned_donor_consent_forms

       #add supplier consent form
       add_unsigned_supplier_consent_forms
       
       #add volunteer consent form
       add_unsigned_volunteer_consent_forms
     
       #add consumer consent form
       add_unsigned_consumer_consent_forms

   end  
    
    def add_unsigned_donor_consent_forms
       donor_consent = ConsentForm.new
       donor_consent.consent_form_type = ConsentFormType.find_by description: "Donor"
       donor_consent.user = self
       donor_consent.save
    end
    
    def add_unsigned_supplier_consent_forms
       supplier_consent = ConsentForm.new
       supplier_consent.consent_form_type = ConsentFormType.find_by description: "Supplier"
       supplier_consent.user = self
       supplier_consent.save
    end
    
    def add_unsigned_volunteer_consent_forms
       volunteer_consent = ConsentForm.new
       volunteer_consent.consent_form_type = ConsentFormType.find_by description: "Volunteer"
       volunteer_consent.user = self  
       volunteer_consent.save
    end
    
    def add_unsigned_consumer_consent_forms
       consumer_consent = ConsentForm.new
       consumer_consent.consent_form_type = ConsentFormType.find_by description: "Donee"
       consumer_consent.user = self  
       consumer_consent.save
    end
    
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user_type.rb
class UserType < ApplicationRecord
    has_many :user
end

app/models/volunteer.rb
class Volunteer < ApplicationRecord
  
    
    def getStartRank
        @@donor_start_Rank||="#{SupplyFoodConfiguration.find_by(name: "Volunteer start rank").description}"
    end
end

app/controllers/address_cocoons_controller.rb
class AddressCocoonsController < ApplicationController
  before_action :set_address_cocoon, only: [:show, :edit, :update, :destroy]

  # GET /address_cocoons
  # GET /address_cocoons.json
  def index
    @address_cocoons = AddressCocoon.all
  end

  # GET /address_cocoons/1
  # GET /address_cocoons/1.json
  def show
  end

  # GET /address_cocoons/new
  def new
    @address_cocoon = AddressCocoon.new
  end

  # GET /address_cocoons/1/edit
  def edit
  end

  # POST /address_cocoons
  # POST /address_cocoons.json
  def create
    @address_cocoon = AddressCocoon.new(address_cocoon_params)

    respond_to do |format|
      if @address_cocoon.save
        format.html { redirect_to @address_cocoon, notice: 'Address cocoon was successfully created.' }
        format.json { render :show, status: :created, location: @address_cocoon }
      else
        format.html { render :new }
        format.json { render json: @address_cocoon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /address_cocoons/1
  # PATCH/PUT /address_cocoons/1.json
  def update
    respond_to do |format|
      if @address_cocoon.update(address_cocoon_params)
        format.html { redirect_to @address_cocoon, notice: 'Address cocoon was successfully updated.' }
        format.json { render :show, status: :ok, location: @address_cocoon }
      else
        format.html { render :edit }
        format.json { render json: @address_cocoon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /address_cocoons/1
  # DELETE /address_cocoons/1.json
  def destroy
    @address_cocoon.destroy
    respond_to do |format|
      format.html { redirect_to address_cocoons_url, notice: 'Address cocoon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address_cocoon
      @address_cocoon = AddressCocoon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def address_cocoon_params
      params.require(:address_cocoon).permit(:line_one, :line_two, :zip_code, :person_cocoon_id)
    end
end

app/helpers/address_cocoons_helper.rb
module AddressCocoonsHelper
end

app/views/address_cocoons/_form.html.erb
<%= form_with(model: address_cocoon, local: true) do |form| %>
  <% if address_cocoon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(address_cocoon.errors.count, "error") %> prohibited this address_cocoon from being saved:</h2>

      <ul>
      <% address_cocoon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :line_one %>
    <%= form.text_field :line_one %>
  </div>

  <div class="field">
    <%= form.label :line_two %>
    <%= form.text_field :line_two %>
  </div>

  <div class="field">
    <%= form.label :zip_code %>
    <%= form.number_field :zip_code %>
  </div>

  <div class="field">
    <%= form.label :person_cocoon_id %>
    <%= form.text_field :person_cocoon_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/address_cocoons/edit.html.erb
<h1>Editing Address Cocoon</h1>

<%= render 'form', address_cocoon: @address_cocoon %>

<%= link_to 'Show', @address_cocoon %> |
<%= link_to 'Back', address_cocoons_path %>

app/views/address_cocoons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Address Cocoons</h1>

<table>
  <thead>
    <tr>
      <th>Line one</th>
      <th>Line two</th>
      <th>Zip code</th>
      <th>Person cocoon</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @address_cocoons.each do |address_cocoon| %>
      <tr>
        <td><%= address_cocoon.line_one %></td>
        <td><%= address_cocoon.line_two %></td>
        <td><%= address_cocoon.zip_code %></td>
        <td><%= address_cocoon.person_cocoon %></td>
        <td><%= link_to 'Show', address_cocoon %></td>
        <td><%= link_to 'Edit', edit_address_cocoon_path(address_cocoon) %></td>
        <td><%= link_to 'Destroy', address_cocoon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Address Cocoon', new_address_cocoon_path %>

app/views/address_cocoons/new.html.erb
<h1>New Address Cocoon</h1>

<%= render 'form', address_cocoon: @address_cocoon %>

<%= link_to 'Back', address_cocoons_path %>

app/views/address_cocoons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Line one:</strong>
  <%= @address_cocoon.line_one %>
</p>

<p>
  <strong>Line two:</strong>
  <%= @address_cocoon.line_two %>
</p>

<p>
  <strong>Zip code:</strong>
  <%= @address_cocoon.zip_code %>
</p>

<p>
  <strong>Person cocoon:</strong>
  <%= @address_cocoon.person_cocoon %>
</p>

<%= link_to 'Edit', edit_address_cocoon_path(@address_cocoon) %> |
<%= link_to 'Back', address_cocoons_path %>